# .github/workflows/test-oidc.yml
name: Test OIDC Connection

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        id: oidc-token
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken()
            console.log('OIDC Token obtained, length:', token.length)
            core.setOutput('token', token)

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubOIDCTest

      - name: Test AWS 
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
          echo "✅ Success! OIDC is working."